char *instrumentname[] = {"1 Grand Piano",
                          "2 Bright Piano",
                          "3 Elec Grand Piano",
                          "4 Honky-tonk Piano",
                          "5 Elec Piano 1",
                          "6 Elec Piano 2",
                          "7 Harpsichord",
                          "8 Clavi",
                          "9 Celesta",
                          "10 Glockenspiel",
                          "11 Music Box",
                          "12 Vibraphone",
                          "13 Marimba",
                          "14 Xylophone",
                          "15 Tubular Bells",
                          "16 Dulcimer",
                          "17 Drawbar Organ",
                          "18 Percussive Organ",
                          "19 Rock Organ",
                          "20 Church Organ",
                          "21 Reed Organ",
                          "22 Accordion",
                          "23 Harmonica",
                          "24 Tango Accordion",
                          "25 Guitar (nylon)",
                          "26 Guitar (steel)",
                          "27 Elec Guitar (jazz)",
                          "28 Elec Guitar (clean)",
                          "29 Elec Guitar (muted)",
                          "30 Overdriven Guitar",
                          "31 Distortion Guitar",
                          "32 Guitar Harmonics",
                          "33 Bass",
                          "34 Elec Bass (finger)",
                          "35 Elec Bass (pick)",
                          "36 Fretless Bass",
                          "37 Slap Bass 1",
                          "38 Slap Bass 2",
                          "39 Synth Bass 1",
                          "40 Synth Bass 2",
                          "41 Violin",
                          "42 Viola",
                          "43 Cello",
                          "44 Contrabass",
                          "45 Tremolo Strings",
                          "46 Pizzicato Strings",
                          "47 Orchestral Harp",
                          "48 Timpani",
                          "49 String Ensembles 1",
                          "50 String Ensembles 2",
                          "51 Synth Strings 1",
                          "52 Synth Strings 2",
                          "53 Choir Aahs",
                          "54 Voice Oohs",
                          "55 Synth Voice",
                          "56 Orchestra Hit",
                          "57 Trumpet",
                          "58 Trombone",
                          "59 Tuba",
                          "60 Muted Trumpet",
                          "61 French Horn",
                          "62 Brass Section",
                          "63 Synth Brass 1",
                          "64 Synth Brass 2",
                          "65 Soprano Sax",
                          "66 Alto Sax",
                          "67 Tenor Sax",
                          "68 Baritone Sax",
                          "69 Oboe",
                          "70 English Horn",
                          "71 Bassoon",
                          "72 Clarinet",
                          "73 Piccolo",
                          "74 Flute",
                          "75 Recorder",
                          "76 Pan Flute",
                          "77 Blown Bottle",
                          "78 Shakuhachi",
                          "79 Whistle",
                          "80 Ocarina",
                          "81 Square Lead (1)",
                          "82 Saw Lead (Lead)",
                          "83 Calliope Lead (3)",
                          "84 Chiff Lead (4)",
                          "85 Charang Lead (5)",
                          "86 Voice Lead (6)",
                          "87 Fifths Lead (7)",
                          "88 Bass + Lead (8)",
                          "89 New Age (Pad 1)",
                          "90 Warm Pad (Pad 2)",
                          "91 Polysynth (Pad 3)",
                          "92 Choir (Pad 4)",
                          "93 Bowed (Pad 5)",
                          "94 Metallic (Pad 6)",
                          "95 Halo (Pad 7)",
                          "96 Sweep (Pad 8)",
                          "97 Rain (FX 1)",
                          "98 Sound Track (2)",
                          "99 Crystal (FX 3)",
                          "100 Atmosphere (4)",
                          "101 Brightness (5)",
                          "102 Goblins (FX 6)",
                          "103 Echoes (FX 7)",
                          "104 Sci-fi (FX 8)",
                          "105 Sitar",
                          "106 Banjo",
                          "107 Shamisen",
                          "108 Koto",
                          "109 Kalimba",
                          "110 Bag Pipe",
                          "111 Fiddle",
                          "112 Shanai",
                          "113 Tinkle Bell",
                          "114 Agogo",
                          "115 Pitched Percuss",
                          "116 Woodblock",
                          "117 Taiko Drum",
                          "118 Melodic Tom",
                          "119 Synth Drum",
                          "120 Reverse Cymbal",
                          "121 Guitar Fret Noise",
                          "122 Breath Noise",
                          "123 Seashore",
                          "124 Bird Tweet",
                          "125 Telephone Ring",
                          "126 Helicopter",
                          "127 Applause",
                          "128 Gunshot"};
int instrumentnumber[] = {1,
                          2,
                          3,
                          4,
                          5,
                          6,
                          7,
                          8,
                          9,
                          10,
                          11,
                          12,
                          13,
                          14,
                          15,
                          16,
                          17,
                          18,
                          19,
                          20,
                          21,
                          22,
                          23,
                          24,
                          25,
                          26,
                          27,
                          28,
                          29,
                          30,
                          31,
                          32,
                          33,
                          34,
                          35,
                          36,
                          37,
                          38,
                          39,
                          40,
                          41,
                          42,
                          43,
                          44,
                          45,
                          46,
                          47,
                          48,
                          49,
                          50,
                          51,
                          52,
                          53,
                          54,
                          55,
                          56,
                          57,
                          58,
                          59,
                          60,
                          61,
                          62,
                          63,
                          64,
                          65,
                          66,
                          67,
                          68,
                          69,
                          70,
                          71,
                          72,
                          73,
                          74,
                          75,
                          76,
                          77,
                          78,
                          79,
                          80,
                          81,
                          82,
                          83,
                          84,
                          85,
                          86,
                          87,
                          88,
                          89,
                          90,
                          91,
                          92,
                          93,
                          94,
                          95,
                          96,
                          97,
                          98,
                          99,
                          100,
                          101,
                          102,
                          103,
                          104,
                          105,
                          106,
                          107,
                          108,
                          109,
                          110,
                          111,
                          112,
                          113,
                          114,
                          115,
                          116,
                          117,
                          118,
                          119,
                          120,
                          121,
                          122,
                          123,
                          124,
                          125,
                          126,
                          127,
                          128};
